In [11]:
import numpy as np         #importing numpy
arr = np.arange(120)       #ndarray creation
arr1 = arr.reshape(2,3,4,5)       #reshaping
print(arr1)
print(arr[91])                #indexing
range = arr[(arr>34)*(arr<40)]
print(range)                       #obtaining a range of value 35-39 from this ndarray
newarr = np.where(arr%5 == 0)
print(newarr)
print("\nmean of arr, axis = 3 : ", np.mean(arr1, axis = 3)) 

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
91
[35 36 37 38 39]
(array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115]),)

mean of arr, axis = 3 :  [[[  2.   7.  12.  17.]
  [ 22.  27.  32.  37.]
  [ 42.  47.  52.  57.]]

 [[ 62.  67.  72.  77.]
  [ 82.  87.  92.  97.]
  [102. 107. 112. 117.]]]
